name: Publish CLI

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  release:
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get tag version
        id: get_tag_version
        run: echo "TAG_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.5.6

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Compile to Linux x86_64
        run: deno task build:linux-x64

      - name: Compile to Linux ARM64
        run: deno task build:linux-arm64

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.get_tag_version.outputs.TAG_VERSION }}
          name: v${{ steps.get_tag_version.outputs.TAG_VERSION }}
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: "build/jiji-dns-linux-x64,build/jiji-dns-linux-arm64"
